name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        cd service/ToDoList
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt

    # - name: Run Tests
    #   run: |
    #     cd service/ToDoList
    #     python3 manage.py test

    - name: Deploy to GitHub Pages
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Configure Git
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        # Fetch all branches
        git fetch origin

        # Check if gh-pages branch exists
        if git show-ref --quiet refs/heads/gh-pages; then
          echo "gh-pages branch exists"
          git checkout gh-pages
          git pull origin gh-pages
        else
          echo "gh-pages branch does not exist. Creating gh-pages branch."
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initial commit on gh-pages branch"
          git push origin gh-pages
          git checkout main
        fi

        # Create a new worktree for the gh-pages branch
        git worktree add /tmp/gh-pages gh-pages

        # Copy the relevant files to the worktree
        cp -r service/ToDoList/* /tmp/gh-pages/

        # Commit and push the changes
        cd /tmp/gh-pages
        git add .
        git commit -m "Deploy to GitHub Pages"
        
        # Pull latest changes from remote gh-pages branch to avoid conflicts
        git pull origin gh-pages --rebase
        
        # Push changes to remote gh-pages branch
        git push origin gh-pages --force
